FROM node

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
	   git \
	&& rm -rf /var/lib/apt/lists/*

RUN npm install -g polymer-cli browser-sync --unsafe-perm

# Create app directory
RUN mkdir -p /opt/sc/static
WORKDIR /opt/sc/static
