version: '2'

services:

  sc-flask:
    build:
      context: ./server/
      dockerfile: docker/Dockerfile-flask
    container_name: 'sc-flask'
    labels:
      application: 'sc-flask'
    env_file:
      - server/env/.base.env
    environment:
      - FLASK_APP=server/app.py
    volumes:
      - socket-volume:/opt/sc/sockets
      - ./server/:/opt/sc/sc-flask
      - working-storage-volume:/opt/sc/storage
      - ./pootle/po:/srv/pootle/po
    expose:
      - '5000'
    depends_on:
      - sc-arangodb

  sc-arangodb:
    image: arangodb/arangodb
    container_name: 'sc-arangodb'
    env_file:
      - server/env/.base.env
    labels:
      application: 'sc-arangodb'
    expose:
      - '8529'
    volumes:
      - db-data-volume:/var/lib/arangodb3

  sc-nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile-nginx
    container_name: 'sc-nginx'
    labels:
      application: 'sc-nginx'
    volumes:
      - ./nginx/conf.d:/etc/nginx/configurations
      - nginx-data-volume:/opt/sc/logs/nginx
      - socket-volume:/opt/sc/sockets
      - l10n-ter:/l10n_ter
      - ./pootle/assets:/opt/sc/pootle/assets
    ports:
      - '80:80'
      - '443:443'
      - '8001:8001'
      - '2052:2052'
    depends_on:
      - sc-flask

  sc-elasticsearch:
    build:
      context: ./elasticsearch/
      dockerfile: Dockerfile-elasticsearch
    container_name: 'sc-elasticsearch'
    labels:
      application: 'sc-elasticsearch'
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 2g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    expose:
      - '9200'
      - '9300'

  sc-swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: 'sc-swagger'
    labels:
      application: 'sc-swagger'
    expose:
      - 8080
    environment:
      - "API_URL=http://localhost/api/swagger.json"

  sc-frontend-tester:
    image: trebuhd/wct-headless:latest
    container_name: 'sc-frontend-tester'
    labels:
      application: 'sc-frontend-tester'

  sc-frontend-builder:
    image: node:8.11.1
    container_name: 'sc-frontend-builder'
    labels:
      application: 'sc-frontend-builder'
    command: npm install
    working_dir: /opt/sc/frontend
    volumes:
      - ./client/:/opt/sc/frontend

  sc-pootle-pipeline:
    build:
      context: ./pootle_pipeline/
      dockerfile: Dockerfile-pootle-pipeline
    container_name: 'sc-pootle-pipeline'
    labels:
      application: 'sc-pootle-pipeline'
    volumes:
      - ./pootle/po/:/srv/pootle/po/
      - ./server/server/:/opt/sc/server/
      - ./client/:/opt/sc/frontend/
      - ./pootle_pipeline/:/opt/sc/po_files/
      
networks:
  default:
    external:
      name: nginx-proxy

volumes:
  db-data-volume:
  nginx-data-volume:
  working-storage-volume:
  socket-volume:
  elasticsearch-data:
  l10n-ter:
