version: '3'

services:
  sc-flask:
    build:
      context: ./server/
      dockerfile: docker/Dockerfile-flask
    container_name: 'sc-flask'
    labels:
      application: 'sc-flask'
    env_file:
      - server/env/.base.env
    environment:
      - FLASK_APP=server/app.py
    volumes:
      - socket-volume:/opt/sc/sockets
      - ./server/:/opt/sc/sc-flask
      - working-storage-volume:/opt/sc/storage
      - sc-data-volume:/opt/sc/sc-flask/sc-data
    expose:
      - '5000'
    depends_on:
      - sc-arangodb

  sc-arangodb:
    image: arangodb/arangodb:3.11.3
    container_name: 'sc-arangodb'
    env_file:
      - server/env/.base.env
    labels:
      application: 'sc-arangodb'
    expose:
      - '8529'
    volumes:
      - db-data-volume:/var/lib/arangodb3

  sc-nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile-nginx
    container_name: 'sc-nginx'
    labels:
      application: 'sc-nginx'
    volumes:
      - ./nginx/conf.d:/etc/nginx/configurations
      - nginx-logs:/opt/sc/logs/nginx
      - socket-volume:/opt/sc/sockets
      - l10n-ter:/l10n_ter
      - nginx-cache:/etc/nginx/cache
    ports:
      - '80:80'
      - '443:443'
      - '8001:8001'
      - '2052:2052'
    depends_on:
      - sc-flask

  sc-swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: 'sc-swagger'
    labels:
      application: 'sc-swagger'
    expose:
      - 8080
    environment:
      - "API_URL=http://localhost/api/swagger.json"

  sc-frontend:
    build:
      context: ./client/
      dockerfile: Dockerfile-frontend
    container_name: 'sc-frontend'
    labels:
      application: 'sc-frontend'
    volumes:
      - sc-data-volume:/opt/sc/sc-data
    working_dir: /opt/sc/frontend
     
  sc-api-tester:
    build:
      context: ./server/api-tester/
      dockerfile: Dockerfile-api-tester
    container_name: 'sc-api-tester'
    network_mode: "host"
    labels:
      application: 'sc-api-tester'
    volumes:
      - ./server/api-tester/:/opt/sc/api-tester/
      
networks:
  default:
    external:
      name: nginx-proxy

volumes:
  db-data-volume:
  nginx-logs:
  sc-data-volume:
  working-storage-volume:
  socket-volume:
  l10n-ter:
  nginx-cache:
