FROM python:3.11.3
COPY --from=ghcr.io/astral-sh/uv:0.9.30 /uv /uvx /bin/

RUN apt-get update && apt-get install -y pngnq && apt-get install -y python3-enchant

RUN mkdir -p /opt/sc/sockets
RUN mkdir -p /opt/sc/sc-flask

# Create a new virtual environment with uv
RUN mkdir -p /opt/sc/venv
WORKDIR /opt/sc/venv
COPY pyproject.toml uv.lock .python-version ./
RUN uv sync --locked
ENV PATH="/opt/sc/venv/.venv/bin:$PATH"

# Copy the remaining application files
WORKDIR /opt/sc/sc-flask
COPY __init__.py entrypoint.sh uwsgi.ini ./
COPY server/ ./server

CMD bash entrypoint.sh