# Using the python image is redundant now that we have a setup with uv.
# Perhaps we should update to something else such as the astral images:
# https://docs.astral.sh/uv/guides/integration/docker/
FROM python:3.11.3

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.9.30 /uv /uvx /bin/


RUN apt-get update && apt-get install -y pngnq && apt-get install -y python3-enchant

RUN mkdir -p /opt/sc/sockets
RUN mkdir -p /opt/sc/sc-flask

WORKDIR /opt/sc/sc-flask

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Omit development dependencies
ENV UV_NO_DEV=1

# Copy the python project files
COPY pyproject.toml uv.lock README.md ./
COPY src/ ./src
COPY tests/ ./tests

# Create a .venv with dependencies and the packages in src/
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

# Make our uv managed .venv the default Python to avoid confusion
# with the system environment provided by the docker image.
# If you run python in the docker container without uv run it
# will still use the .venv
ENV PATH="/opt/sc/sc-flask/.venv/bin:$PATH"

# Copy over the remaining files required to run the application.
COPY entrypoint.sh uwsgi.ini ./

# Some commands such as sc_flask.manage require FLASK_APP to be set.
# Flask and uwsgi do not.
ENV FLASK_APP="sc_flask.wsgi:app"

CMD ["bash", "entrypoint.sh"]