[project]
name = "sc-flask"
version = "0.1.0"
description = "The backend python implementation for SuttaCentral.net"
readme = "README.md"
requires-python = "==3.11.3"
dependencies = [
    "aksharamukha==2.3",
    "algoliasearch==3.0.0",
    "beautifulsoup4==4.11.1",
    "click==8.1.3",
    "decorator==5.1.1",
    "faker==15.3.4",
    "flasgger==0.9.5",
    "flask==2.2.5",
    "flask-caching==2.0.1",
    "flask-cors==3.0.10",
    "flask-restful==0.3.9",
    "fonttools==4.38.0",
    "jinja2==3.1.2",
    "lxml==4.9.1",
    "pytest==7.2.0",
    "pytest-flask==1.2.0",
    "pytest-sugar==0.9.6",
    "python-arango==7.5.3",
    "regex==2022.10.31",
    "requests==2.31.0",
    "sortedcontainers==2.4.0",
    "stripe==6.4.0",
    "tqdm==4.64.1",
    "unidecode==1.3.7",
    "uwsgi==2.0.21",
    "zhconv==1.4.3",
]

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]
