FROM ghcr.io/astral-sh/uv:debian-slim

COPY pyproject.toml README.md uv.lock /

RUN --mount=type=cache,target=/root/.cache/uv \
    ["uv", "sync", "--locked", "--no-install-project"]

COPY tests/ ./tests

ENTRYPOINT ["uv", "run", "pytest"]