FROM nginx:1.12.1

RUN mkdir -p /opt/sc/sockets

RUN rm /etc/nginx/conf.d/default.conf

ADD conf.d/ /etc/nginx/configurations

COPY '*.sh' ./

RUN apt update && apt install -y \
    curl \
    make \
    g++ \
    gnupg

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt install -y nodejs
RUN npm install -g polymer-cli
