FROM python:3.13.0b4
RUN apt-get update && apt-get install -y pngnq && apt-get install -y python3-enchant
RUN mkdir -p /opt/sc/sockets
RUN mkdir -p /opt/sc/sc-flask
WORKDIR /opt/sc/sc-flask
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY *.* ./
